### ISSUE TITLE
symfony/console > 7 issue 

### ISSUE THREAD

**Issue by arhimede** [dotkernel/dot-cli#26]
return an error for symfony/console > 7.0

**Command name "" is invalid.**

**Comment by arhimede** [comment]
for the moment, symfony/console is set hardcoded to 6.4.2

**Comment by arhimede** [comment]
@MarioRadu check what laminas-cli is doing extra over symfony/console 
https://github.com/laminas/laminas-cli/blob/1.11.x/src/Command/AbstractParamAwareCommand.php

**Comment by marioradu05** [comment]
Fixed in https://github.com/dotkernel/dot-cli/pull/27.
