### ISSUE TITLE
List all commands throws an exception

### ISSUE THREAD

**Issue by alexmerlin** [dotkernel/dot-cli#7]
Running `php ./bin/cli.php` throws an exception.

**Expected behaviour:**
Output a list of all available commands

**Actual output:**

> PHP Fatal error:  Uncaught TypeError: str_replace(): Argument #3 ($subject) must be of type array|string, null given in vendor/dotkernel/dot-cli/src/FileLocker.php:124

**Comment by arhimede** [comment]
@alexmerlin  can you draft a release ?

**Comment by alexmerlin** [comment]
> @alexmerlin can you draft a release ?

Done.
https://github.com/dotkernel/dot-cli/releases/tag/3.2.1

**Comment by alexmerlin** [comment]
Fixed in #8
